#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>



#include "regex.h"

/*
    char* make_range() -
        Input parameters = 
            - char* regex -> the regular expression
        Output = 
            - char* range -> String of all characters accepted by the regular expression, in increasing ASCII value order
*/

char* make_range(char* reg){ 
    // reg of form [x-y]* or [x-y]+ or [x-y]
    int start = reg[1];
    int end = reg[3];
    char* range = malloc((end - start + 2) * sizeof(char)); // todo - check for null character
    
    if(start > end) {
        printf("Start of range can't be more than end");
        return "-1";
    }
    
    for(int i=start; i<=end; i++){
        range[i-start] = (char)(reg[1] + i - start);
    }

    range[end - start + 1] = '\0';
    return range;
}

/*
    long long find_freq() - 
        Input parameters =
            - char* regex -> the regular expression
        Output = 
            - long long freq -> a long long number denoting the frequecy of the parts of the regex, in reverse order (leftmost part of regex is the LSB of freq).
                                if regex = [a-z][a-z][1-5]*[a-z], freq = 1211 (1 for parts without *, 2 for parts with *) 

*/

long long find_freq(char* regex) {
    long long freq = 0;
    for(int i=0; i<strlen(regex); i++){
        if(regex[i] == ']' && regex[i+1] == '[') freq = freq*10 + 1; // [x-y]
        else if(regex[i] == ']' && regex[i+1] == '*') freq = freq*10 + 2; // [x-y]*
        // for [x-y]+ use [x-y][x-y]*
    }
    long long rev_freq = 0;
    while(freq != 0){
        int rem = freq % 10;
        rev_freq = rev_freq * 10 + rem;
        freq = freq / 10;
    }
    return rev_freq;
}

/*
    char* substr() - 
        Input parameters =
            - char* regex -> the regular expression
            - int start -> the starting index
        Output = 
            - char* subs -> the substring of the regex, starting from index start, and taking 5 characters
                            if regex = [2-5][6-7]*[a-z] and start = 5, subs = [6-7]
*/

char* substr(char* regex, int start) {
    char* subs = malloc(6 * sizeof(char));
    for(int i=0; i<5; i++){
        subs[i] = regex[start + i];
    }
    return subs;
}

/*
    char** divide_regex() - 
        Input parameters =
            - char* regex -> the regular expression
        Output = 
            - char** parts -> an array of the different parts of the regex
                              if regex = [a-z][0-9]*[p-q]*, parts[0] = [a-z], parts[1] = [0-9], parts[2] = [p-q]
*/

char** divide_regex(char* regex){
    int num_of_parts = 0;
    for(int i=0; i<strlen(regex); i++){
        if(regex[i] == ']') num_of_parts++;
    }
    char** parts = calloc(num_of_parts, sizeof(char*));
    int ptr = 0;    
    for(int i=0; i<num_of_parts;){
        if(regex[ptr] == '['){
            char* subs = substr(regex, ptr);
            char* ran = make_range(subs);
            parts[i] = ran;
            i++;
        }
        ptr++;
    }
    return parts;
}
 
/*
    bool search() - 
        Input parameters =
            - char* regex -> the regular expression
            - char ele -> the character that has to be checked if it is present in the range
        Output = 
            - bool present -> true if the character is present in that range
*/

bool search(char* range, char ele){
    return ((ele <= range[strlen(range) - 1]) && (ele >= range[0]));
}

/*
    bool end_of_regex() - 
        Input parameters =
            - long long freq -> the frequency number (calculated by find_freq)
        Output = 
            - bool at_end -> returns true if we CAN be at the end of the regex
                             if regex = [a-z], and we have read one char, we are at the end
                             if regex = [0-9]*, and we have read no chars, we can be at the end
*/

bool end_of_regex(long long freq){
    while (freq){
        if(freq % 10 == 1) return false;
        freq /= 10;
    }
    return true;
} 

/*
    int check() - 
        Input parameters =
            - char* regex -> the regular expression
            - char* expr -> the expression that we want to check, whether it can be generated by the above regex
        Output = 
            - int out -> 0 if it cannot be generated, 1 if it can
*/

int check(char* regex, char* expr){
    char** parts = divide_regex(regex);
    int expr_ptr = 0;
    int id = 0;

    long long freq = find_freq(regex);

    while(true){
        printf("%c -> ", expr[expr_ptr]);
        
        if(end_of_regex(freq) && expr == ""){
            printf("Empty string part of language.\n");
            return 1;
        }

        if(id == sizeof(parts)) break;
        else if(freq == 0 && expr_ptr != strlen(expr) - 1) {
            printf("in cond 1\n");
            printf("At end of regex, but expression is still left.\n");
            printf("Invalid.\n");
            return 0;
        }
        else if(expr_ptr == strlen(expr) - 1 && !end_of_regex(freq/10)) {
            printf("in cond 2\n");
            printf("At end of expression, but regex has more terms.\n");
            printf("Invalid.\n");
            return 0;
        }
        else if(expr_ptr == strlen(expr) - 1 && end_of_regex(freq/10)) {
            if(search(parts[id], expr[expr_ptr])) break;
            else {
                printf("Invalid\n");
                return 0;
            }
        }
        else if(freq%10 == 1 && search(parts[id], expr[expr_ptr])){
            printf("in cond 3\n");
            id++;
            expr_ptr++;
            freq/=10;
        }
        else if(freq%10 == 1 && !search(parts[id], expr[expr_ptr])){
            printf("in cond 4\n");
            printf("Failed because of absence of necessary part of regex.\n");
            return 0;
        }
        else if(freq%10 == 2 && search(parts[id], expr[expr_ptr])){
            printf("in cond 5\n");
            expr_ptr++;
        }
        else if(freq%10 == 2 && !search(parts[id], expr[expr_ptr])){
            printf("in cond 6\n");
            id++;
            freq/=10;
        }
    }

    if(end_of_regex(freq)) {
        printf("Valid\n");
        return 1;
    }
    printf("Invalid\n");
    return 0;

}

int main(void) {

    char *regex = "[a-z]*";

    check(regex, "testing");
    check(regex, "yo!");
    check(regex, "");
    check(regex, "hell0");

    // char* regex = "[2-7][2-7][2-7][2-7]";
    // check(regex, "222");


    // char* regex = "[b-d][2-7][b-d]*[2-7]*";
    // bool check1 = check(regex, "b2565");
    // printf("\n\n\n");
    // bool check2 = check(regex, "b2bccd");
    // printf("\n\n\n");
    // bool check3 = check(regex, "b2bccddc7667");
    // printf("\n\n\n");
    // printf("\n\n\n");
    // bool check5 = check(regex, "2");
    // printf("\n\n\n");
    // bool check6 = check(regex, "b");
}
